### ISSUE TITLE
Verbe « Adire »

### ISSUE THREAD

**Issue by necropotame** [RadicaliseesSurInternet/hunspell-inclusif#2]
Il semble que ça n'existe pas et remplace le verbe « adirer », pourtant également présent dans le dictionnaire, mais pas conjugué à tout les temps.

https://cooljugator.com/fr/adirer
https://cooljugator.com/fr/dire
https://cooljugator.com/fr/adire

**Comment by ariasuni** [comment]
Ce dépôt ne gère que l’ajout d’écritures et mots en forme dite inclusive. Pour les autres problèmes, il faut s’adresser au [projet Dicollecte](https://www.dicollecte.org/home.php?prj=fr).

Le verbe adire n’existe pas sur le site que tu donnes, mais [xiste bien sur Dicollecte](https://www.dicollecte.org/entry.php?prj=fr&id=126668). Si tu penses qu’il manque des conjugaisons ou qu’il y a des erreurs, alors fait leur un retour, ils sont réactifs.
